version: '3.8'

services:
  # Orthanc PACS server
  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthanc_server
    volumes:
      # Configuration
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persistent storage
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    restart: unless-stopped
    ports:
      - '4242:4242' # Orthanc DICOM port
      - '8042:8042' # Orthanc HTTP port
